import React from 'react';

const FixYourCity = () => (
  <div>
    <section className="fix-your-city">
      <h2>
        <a href="https://fix-your-city.herokuapp.com/" target="_blank">
          Fix Your City
        </a>
      </h2>
      <div className="fyc-sections">
        <section className="fyc-words">
          <p>
            In June of 2018 some friends and I entered the&nbsp;
            <a href="NYC Developer Week Hackathon" target="_blank">
              NYC Developer Week Hackathon
            </a>.
          </p>
          <p>
            In response to the TomTom challenge to make an app for smart cities,
            we created Fix Your City.
          </p>
          <p>
            This (WIP) app allows users to upload photos of infrastruture
            problems they encounter in their day-to-day lives. The incident gets
            marked on a map generated by the TomTom api.
          </p>
          <p>
            My proudest contribution to this project was implementing a{' '}
            <a
              href="https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow"
              target="_blank">
              Feature Branch Workflow
            </a>{' '}
            so multiple developers on the team could build features
            independently withouth disturbing the codebase.
          </p>
        </section>
        <div className="fyc-screenshot-holder">
          <img src="./images/fix_your_city.png" className="fyc-screenshot" />
        </div>
      </div>
    </section>
    <hr />
  </div>
);

export default FixYourCity;
